# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 183a538009fefb39df665ee1d8e0346b250d6ae2abf7aa34a9680c1814fb7ebd1c552720ea61d226f35194067f35e1a0a8679691dc7c9fdbabf03c992a7bb8dd

test:
  secret_key_base: 577843c5286398827b7ef255bf79725feb32305fe0b0f3d4447e05b7302ac5c636bf1de8114891412fe079437c491b1629fa8d6d89b0bc861b81d7eb4f6eb55c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
